CREATE TABLE forecast_vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    choice VARCHAR(10) NOT NULL,
    CONSTRAINT uq_forecast_user UNIQUE (forecast_id, user_id),
    CONSTRAINT valid_choice CHECK (choice IN ('BUY', 'HOLD', 'SELL'))
);
