-- ETF Orca 앱 스키마. 설계는 docs/erd.md, 이 파일이 정본이다. Hibernate 는 validate 만 한다.
-- FK 제약은 걸지 않는다. 참조 컬럼은 ID 만 저장하고 자식 정리는 서비스가 같은 트랜잭션에서 한다.
-- 쓰기 소유 테이블은 앱이 만들고, 읽기 전용 동기화 테이블은 파이프라인 산출물을 옮긴 것이라 앱은 읽기만 한다.

-- ───────────────────────── 쓰기 소유 ─────────────────────────

CREATE TABLE member (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(255),
    password_hash           VARCHAR(100),
    provider                VARCHAR(10)  NOT NULL,
    provider_subject        VARCHAR(255),
    nick                    VARCHAR(30)  NOT NULL,
    handle                  VARCHAR(30)  NOT NULL,
    disclaimer_accepted_at  TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at              TIMESTAMPTZ,
    CONSTRAINT uq_member_email UNIQUE (email),
    CONSTRAINT uq_member_handle UNIQUE (handle),
    CONSTRAINT uq_member_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT ck_member_provider CHECK (provider IN ('email', 'apple', 'google'))
);
-- 탈퇴 시 deleted_at 을 채우고 email·password_hash·provider_subject 를 NULL 로 지운다. 행은 남긴다.

CREATE TABLE device (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_key    VARCHAR(64)  NOT NULL,
    member_id     BIGINT,
    push_token    VARCHAR(255),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_device_key UNIQUE (device_key)
);

-- 게스트(디바이스)와 회원을 한 종류의 소유자로 본다. 관심·알림·온보딩은 principal_id 하나만 가진다.
CREATE TABLE principal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        VARCHAR(10)  NOT NULL,
    member_id   BIGINT,
    device_id   BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_principal_member UNIQUE (member_id),
    CONSTRAINT uq_principal_device UNIQUE (device_id),
    CONSTRAINT ck_principal_kind CHECK (
        (kind = 'member' AND member_id IS NOT NULL AND device_id IS NULL)
        OR (kind = 'device' AND device_id IS NOT NULL AND member_id IS NULL)
    )
);

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT       NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL,
    device_id   BIGINT,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_token_member ON refresh_token (member_id);

CREATE TABLE watch_group (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id  BIGINT       NOT NULL,
    key           VARCHAR(20)  NOT NULL,
    label         VARCHAR(30)  NOT NULL,
    position      SMALLINT     NOT NULL DEFAULT 0,
    is_default    BOOLEAN      NOT NULL DEFAULT false,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_watch_group_key UNIQUE (principal_id, key)
);
CREATE UNIQUE INDEX uq_watch_group_default ON watch_group (principal_id) WHERE is_default;

CREATE TABLE watch_item (
    group_id    BIGINT       NOT NULL,
    etf_code    VARCHAR(6)   NOT NULL,
    position    SMALLINT     NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (group_id, etf_code)
);
CREATE INDEX ix_watch_item_etf ON watch_item (etf_code);

CREATE TABLE principal_theme (
    principal_id  BIGINT       NOT NULL,
    theme_key     VARCHAR(30)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (principal_id, theme_key)
);

CREATE TABLE alert_etf (
    principal_id  BIGINT       NOT NULL,
    etf_code      VARCHAR(6)   NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (principal_id, etf_code)
);

CREATE TABLE notification (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id  BIGINT       NOT NULL,
    kind          VARCHAR(10)  NOT NULL,
    etf_code      VARCHAR(6),
    post_id       BIGINT,
    title         TEXT         NOT NULL,
    body          TEXT         NOT NULL,
    read_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_notification_kind CHECK (kind IN ('watch', 'signal', 'content', 'comm'))
);
CREATE INDEX ix_notification_feed ON notification (principal_id, created_at DESC, id DESC);
CREATE INDEX ix_notification_unread ON notification (principal_id) WHERE read_at IS NULL;

CREATE TABLE post (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id     BIGINT        NOT NULL,
    etf_code      VARCHAR(6)    NOT NULL,
    title         VARCHAR(100),
    body          VARCHAR(280)  NOT NULL,
    quote_tag     VARCHAR(30),
    repost_of_id  BIGINT,
    like_count    INTEGER       NOT NULL DEFAULT 0,
    reply_count   INTEGER       NOT NULL DEFAULT 0,
    repost_count  INTEGER       NOT NULL DEFAULT 0,
    view_count    INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE INDEX ix_post_feed ON post (created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX ix_post_etf ON post (etf_code, created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX ix_post_author ON post (author_id, created_at DESC);

CREATE TABLE post_tag (
    post_id   BIGINT      NOT NULL,
    etf_code  VARCHAR(6)  NOT NULL,
    position  SMALLINT    NOT NULL DEFAULT 0,
    PRIMARY KEY (post_id, etf_code)
);
CREATE INDEX ix_post_tag_etf ON post_tag (etf_code);

CREATE TABLE reply (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT        NOT NULL,
    author_id   BIGINT        NOT NULL,
    body        VARCHAR(280)  NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ
);
CREATE INDEX ix_reply_post ON reply (post_id, created_at, id);

CREATE TABLE post_like (
    post_id     BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (post_id, member_id)
);

-- 실험용 forecast_vote 를 폐기하고 ETF 코드·회원 기준으로 재정의한다. 실험 데이터는 버린다.
DROP TABLE forecast_vote;
CREATE TABLE vote (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etf_code    VARCHAR(6)   NOT NULL,
    member_id   BIGINT       NOT NULL,
    choice      VARCHAR(5)   NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_vote_etf_member UNIQUE (etf_code, member_id),
    CONSTRAINT ck_vote_choice CHECK (choice IN ('buy', 'wait', 'sell'))
);

-- ───────────────────────── 읽기 전용 동기화 ─────────────────────────
-- 표 데이터는 정규화, 분석 산출물은 키 컬럼 + 파이프라인 발행본 원문 JSONB.
-- 앱 계약 형태로의 변환은 서비스가 읽을 때 한다. 발행본은 (대상, as_of) 당 최신 1행.

CREATE TABLE theme (
    key         VARCHAR(30)  PRIMARY KEY,
    concept_id  TEXT,
    label       VARCHAR(30)  NOT NULL,
    "group"     VARCHAR(10)  NOT NULL,
    hot         BOOLEAN      NOT NULL DEFAULT false,
    position    SMALLINT     NOT NULL DEFAULT 0,
    synced_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_theme_concept UNIQUE (concept_id),
    CONSTRAINT ck_theme_group CHECK ("group" IN ('industry', 'asset'))
);

-- code 는 앱 키(KRX 6자리), instrument_id 는 파이프라인 키(ULID). 코드는 시장(market_code) 안에서만 유일하다.
CREATE TABLE etf (
    code           VARCHAR(6)    PRIMARY KEY,
    instrument_id  TEXT          NOT NULL,
    market_code    VARCHAR(30)   NOT NULL,
    name           VARCHAR(100)  NOT NULL,
    theme_key      VARCHAR(30)   NOT NULL,
    sub            VARCHAR(100),
    hot            BOOLEAN       NOT NULL DEFAULT false,
    synced_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_etf_instrument UNIQUE (instrument_id)
);

CREATE TABLE etf_quote (
    etf_code    VARCHAR(6)     PRIMARY KEY,
    price       NUMERIC(14,2)  NOT NULL,
    change_pct  NUMERIC(6,2)   NOT NULL,
    as_of       TIMESTAMPTZ    NOT NULL,
    synced_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE etf_candle (
    etf_code    VARCHAR(6)     NOT NULL,
    trade_date  DATE           NOT NULL,
    open        NUMERIC(14,2)  NOT NULL,
    high        NUMERIC(14,2)  NOT NULL,
    low         NUMERIC(14,2)  NOT NULL,
    close       NUMERIC(14,2)  NOT NULL,
    volume      BIGINT,
    PRIMARY KEY (etf_code, trade_date)
);

-- 오늘 움직임 발행본. payload = 서버 조합본 {summary, items[]}.
CREATE TABLE etf_move (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etf_code      VARCHAR(6)   NOT NULL,
    as_of         DATE         NOT NULL,
    published_at  TIMESTAMPTZ  NOT NULL,
    payload       JSONB        NOT NULL,
    synced_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_etf_move_day UNIQUE (etf_code, as_of)
);

-- 전망 발행본. payload = {outlook, summary_card, detail, factors, conclusion, publication}.
-- signal 은 outlook.direction 을 5단계로 접은 값이다.
CREATE TABLE etf_analysis (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etf_code      VARCHAR(6)   NOT NULL,
    as_of         DATE         NOT NULL,
    published_at  TIMESTAMPTZ  NOT NULL,
    signal        VARCHAR(10)  NOT NULL,
    payload       JSONB        NOT NULL,
    synced_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_etf_analysis_day UNIQUE (etf_code, as_of),
    CONSTRAINT ck_etf_analysis_signal CHECK (signal IN ('strongDown', 'down', 'neutral', 'up', 'strongUp'))
);

-- 5요인 상세. 축별 독립 응답이라 행을 나눈다. 행이 없으면 준비 중(ANALYSIS4041).
CREATE TABLE etf_analysis_axis (
    etf_analysis_id  BIGINT      NOT NULL,
    axis             VARCHAR(6)  NOT NULL,
    dir              VARCHAR(8)  NOT NULL,
    payload          JSONB       NOT NULL,
    PRIMARY KEY (etf_analysis_id, axis),
    CONSTRAINT ck_etf_analysis_axis_axis CHECK (axis IN ('issue', 'chart', 'macro', 'value', 'flow')),
    CONSTRAINT ck_etf_analysis_axis_dir CHECK (dir IN ('help', 'neutral', 'burden'))
);

CREATE TABLE issue (
    id            VARCHAR(64)   PRIMARY KEY,
    as_of         DATE          NOT NULL,
    rank          INTEGER       NOT NULL,
    delta         INTEGER       NOT NULL DEFAULT 0,
    title         VARCHAR(100)  NOT NULL,
    kw            VARCHAR(50)   NOT NULL,
    etf_code      VARCHAR(6),
    published_at  TIMESTAMPTZ   NOT NULL,
    payload       JSONB         NOT NULL,
    synced_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_issue_rank ON issue (as_of DESC, rank);

-- payload.affected[] 의 ETF 를 키로 뽑은 것. tab=mine 필터용.
CREATE TABLE issue_etf (
    issue_id  VARCHAR(64)  NOT NULL,
    etf_code  VARCHAR(6)   NOT NULL,
    PRIMARY KEY (issue_id, etf_code)
);
CREATE INDEX ix_issue_etf_etf ON issue_etf (etf_code);

CREATE TABLE theme_detail (
    theme_key     VARCHAR(30)   NOT NULL,
    as_of         DATE          NOT NULL,
    published_at  TIMESTAMPTZ   NOT NULL,
    dir           VARCHAR(8)    NOT NULL,
    headline      VARCHAR(200)  NOT NULL,
    payload       JSONB         NOT NULL,
    synced_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (theme_key, as_of),
    CONSTRAINT ck_theme_detail_dir CHECK (dir IN ('help', 'neutral', 'burden'))
);

CREATE TABLE etf_rank (
    as_of     DATE          NOT NULL,
    rank      SMALLINT      NOT NULL,
    etf_code  VARCHAR(6)    NOT NULL,
    title     VARCHAR(100)  NOT NULL,
    chips     JSONB         NOT NULL DEFAULT '[]',
    ready     BOOLEAN       NOT NULL DEFAULT true,
    PRIMARY KEY (as_of, rank)
);

CREATE TABLE etf_detail (
    etf_code   VARCHAR(6)   PRIMARY KEY,
    as_of      DATE         NOT NULL,
    payload    JSONB        NOT NULL,
    synced_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE etf_story (
    etf_code      VARCHAR(6)   NOT NULL,
    as_of         DATE         NOT NULL,
    published_at  TIMESTAMPTZ  NOT NULL,
    payload       JSONB        NOT NULL,
    synced_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (etf_code, as_of)
);
