-- 커뮤니티 신고와 회원 차단. 처리는 운영자 메일 확인 후 DB 소프트 삭제.
CREATE TABLE report (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_member_id  BIGINT       NOT NULL,
    target_type         VARCHAR(10)  NOT NULL,
    target_id           BIGINT       NOT NULL,
    reason              VARCHAR(10)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_report_target_type CHECK (target_type IN ('post', 'reply')),
    CONSTRAINT ck_report_reason CHECK (reason IN ('spam', 'abuse', 'sexual', 'scam', 'etc')),
    CONSTRAINT uq_report_target UNIQUE (reporter_member_id, target_type, target_id)
);

-- 단방향 차단. blocker 에게 blocked 의 글·답글·답글 알림을 숨긴다.
CREATE TABLE member_block (
    blocker_id  BIGINT       NOT NULL,
    blocked_id  BIGINT       NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (blocker_id, blocked_id)
);
