-- 기관 엔티티 시드 — 규제기관·법원·중앙은행·시장기관 68곳.
--
-- 왜 필요한가: event_argument.entity_id 는 NOT NULL + FK → entity 다. 그래서 AUTHORITY·
-- COURT·CENTRAL_BANK 처럼 티커가 없는 참여자는 해소할 대상 행 자체가 없어 적재에서
-- 통째로 빠졌다(assemble_events 의 "미해소 참여자는 event_argument 에 못 싣는다").
-- 그 역할들을 identity 로 쓰는 타입(LEGAL.REGULATORY_ACTION·PRODUCT.CERTIFICATION·
-- POLICY.* 등)은 결과적으로 novelty_status 가 100% UNKNOWN 이었다.
--
-- 정본은 edge_ontology resources/entity/authority_registry_v0_1.yaml 이다. 이 파일은 그 레지스트리의
-- 투영이며 test_ontology 가 둘의 일치를 강제한다 — 한쪽만 고치면 테스트가 깨진다.
-- entity_id 는 해시가 아니라 레지스트리에 적힌 읽을 수 있는 고정 문자열이다:
-- SQL 과 파이썬이 같은 값에 도달해야 하는데, 양쪽에서 해시를 계산하면 갈릴 수 있다.
--
-- actor_type 은 기존 CHECK(V202607150001 ck_actor_type) 안의 값만 쓴다 — 스키마 변경 없음.
-- entity 와 actor 는 같은 ID 를 쓴다(FK 가 (actor_id, entity_type) → (entity_id, entity_type)).

INSERT INTO entity (entity_id, entity_type, display_name, status) VALUES
    ('actor_auth_kr_ftc', 'ACTOR', '공정거래위원회', 'ACTIVE'),
    ('actor_auth_kr_fsc', 'ACTOR', '금융위원회', 'ACTIVE'),
    ('actor_auth_kr_fss', 'ACTOR', '금융감독원', 'ACTIVE'),
    ('actor_auth_kr_mfds', 'ACTOR', '식품의약품안전처', 'ACTIVE'),
    ('actor_auth_kr_motie', 'ACTOR', '산업통상자원부', 'ACTIVE'),
    ('actor_auth_kr_msit', 'ACTOR', '과학기술정보통신부', 'ACTIVE'),
    ('actor_auth_kr_moef', 'ACTOR', '기획재정부', 'ACTIVE'),
    ('actor_auth_kr_molit', 'ACTOR', '국토교통부', 'ACTIVE'),
    ('actor_auth_kr_me', 'ACTOR', '환경부', 'ACTIVE'),
    ('actor_auth_kr_moel', 'ACTOR', '고용노동부', 'ACTIVE'),
    ('actor_auth_kr_mohw', 'ACTOR', '보건복지부', 'ACTIVE'),
    ('actor_auth_kr_mnd', 'ACTOR', '국방부', 'ACTIVE'),
    ('actor_auth_kr_dapa', 'ACTOR', '방위사업청', 'ACTIVE'),
    ('actor_auth_kr_kipo', 'ACTOR', '특허청', 'ACTIVE'),
    ('actor_auth_kr_customs', 'ACTOR', '관세청', 'ACTIVE'),
    ('actor_auth_kr_nts', 'ACTOR', '국세청', 'ACTIVE'),
    ('actor_auth_kr_kcc', 'ACTOR', '방송통신위원회', 'ACTIVE'),
    ('actor_auth_kr_pipc', 'ACTOR', '개인정보보호위원회', 'ACTIVE'),
    ('actor_auth_kr_nssc', 'ACTOR', '원자력안전위원회', 'ACTIVE'),
    ('actor_auth_kr_sflec', 'ACTOR', '증권선물위원회', 'ACTIVE'),
    ('actor_auth_kr_prosecution', 'ACTOR', '대검찰청', 'ACTIVE'),
    ('actor_auth_kr_police', 'ACTOR', '경찰청', 'ACTIVE'),
    ('actor_auth_kr_moe', 'ACTOR', '교육부', 'ACTIVE'),
    ('actor_auth_kr_mofa', 'ACTOR', '외교부', 'ACTIVE'),
    ('actor_auth_kr_mou', 'ACTOR', '통일부', 'ACTIVE'),
    ('actor_auth_kr_moj', 'ACTOR', '법무부', 'ACTIVE'),
    ('actor_auth_kr_mois', 'ACTOR', '행정안전부', 'ACTIVE'),
    ('actor_auth_kr_mcst', 'ACTOR', '문화체육관광부', 'ACTIVE'),
    ('actor_auth_kr_mafra', 'ACTOR', '농림축산식품부', 'ACTIVE'),
    ('actor_auth_kr_mof', 'ACTOR', '해양수산부', 'ACTIVE'),
    ('actor_auth_kr_mss', 'ACTOR', '중소벤처기업부', 'ACTIVE'),
    ('actor_auth_kr_mogef', 'ACTOR', '여성가족부', 'ACTIVE'),
    ('actor_auth_kr_mpva', 'ACTOR', '국가보훈부', 'ACTIVE'),
    ('actor_auth_kr_paps', 'ACTOR', '조달청', 'ACTIVE'),
    ('actor_auth_kr_kostat', 'ACTOR', '통계청', 'ACTIVE'),
    ('actor_auth_kr_kma', 'ACTOR', '기상청', 'ACTIVE'),
    ('actor_auth_kr_forest', 'ACTOR', '산림청', 'ACTIVE'),
    ('actor_auth_kr_kasa', 'ACTOR', '우주항공청', 'ACTIVE'),
    ('actor_auth_kr_kdca', 'ACTOR', '질병관리청', 'ACTIVE'),
    ('actor_auth_kr_nfa', 'ACTOR', '소방청', 'ACTIVE'),
    ('actor_auth_kr_kcg', 'ACTOR', '해양경찰청', 'ACTIVE'),
    ('actor_auth_kr_mma', 'ACTOR', '병무청', 'ACTIVE'),
    ('actor_court_kr_supreme', 'ACTOR', '대법원', 'ACTIVE'),
    ('actor_court_kr_constitutional', 'ACTOR', '헌법재판소', 'ACTIVE'),
    ('actor_court_kr_seoul_central', 'ACTOR', '서울중앙지방법원', 'ACTIVE'),
    ('actor_court_kr_seoul_high', 'ACTOR', '서울고등법원', 'ACTIVE'),
    ('actor_court_kr_patent', 'ACTOR', '특허법원', 'ACTIVE'),
    ('actor_cb_kr_bok', 'ACTOR', '한국은행', 'ACTIVE'),
    ('actor_cb_us_fed', 'ACTOR', '미국 연방준비제도', 'ACTIVE'),
    ('actor_cb_eu_ecb', 'ACTOR', '유럽중앙은행', 'ACTIVE'),
    ('actor_cb_jp_boj', 'ACTOR', '일본은행', 'ACTIVE'),
    ('actor_inst_kr_krx', 'ACTOR', '한국거래소', 'ACTIVE'),
    ('actor_inst_kr_ksd', 'ACTOR', '한국예탁결제원', 'ACTIVE'),
    ('actor_inst_kr_nps', 'ACTOR', '국민연금공단', 'ACTIVE'),
    ('actor_inst_kr_kdb', 'ACTOR', '한국산업은행', 'ACTIVE'),
    ('actor_inst_kr_nice', 'ACTOR', 'NICE신용평가', 'ACTIVE'),
    ('actor_inst_kr_kis', 'ACTOR', '한국신용평가', 'ACTIVE'),
    ('actor_inst_kr_kr_ratings', 'ACTOR', '한국기업평가', 'ACTIVE'),
    ('actor_inst_kr_kftc', 'ACTOR', '금융결제원', 'ACTIVE'),
    ('actor_inst_kr_dtaq', 'ACTOR', '국방기술품질원', 'ACTIVE'),
    ('actor_inst_kr_kisa', 'ACTOR', '한국인터넷진흥원', 'ACTIVE'),
    ('actor_auth_us_sec', 'ACTOR', '미국 증권거래위원회', 'ACTIVE'),
    ('actor_auth_us_fda', 'ACTOR', '미국 식품의약국', 'ACTIVE'),
    ('actor_auth_us_ftc', 'ACTOR', '미국 연방거래위원회', 'ACTIVE'),
    ('actor_auth_us_doc', 'ACTOR', '미국 상무부', 'ACTIVE'),
    ('actor_auth_us_doj', 'ACTOR', '미국 법무부', 'ACTIVE'),
    ('actor_auth_eu_commission', 'ACTOR', '유럽연합 집행위원회', 'ACTIVE'),
    ('actor_auth_cn_samr', 'ACTOR', '중국 국가시장감독관리총국', 'ACTIVE')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO actor (actor_id, actor_type, country_code) VALUES
    ('actor_auth_kr_ftc', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_fsc', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_fss', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mfds', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_motie', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_msit', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_moef', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_molit', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_me', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_moel', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mohw', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mnd', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_dapa', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kipo', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_customs', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_nts', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kcc', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_pipc', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_nssc', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_sflec', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_prosecution', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_police', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_moe', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mofa', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mou', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_moj', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mois', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mcst', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mafra', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mof', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mss', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mogef', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mpva', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_paps', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kostat', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kma', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_forest', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kasa', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kdca', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_nfa', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_kcg', 'GOVERNMENT', 'KR'),
    ('actor_auth_kr_mma', 'GOVERNMENT', 'KR'),
    ('actor_court_kr_supreme', 'GOVERNMENT', 'KR'),
    ('actor_court_kr_constitutional', 'GOVERNMENT', 'KR'),
    ('actor_court_kr_seoul_central', 'GOVERNMENT', 'KR'),
    ('actor_court_kr_seoul_high', 'GOVERNMENT', 'KR'),
    ('actor_court_kr_patent', 'GOVERNMENT', 'KR'),
    ('actor_cb_kr_bok', 'GOVERNMENT', 'KR'),
    ('actor_cb_us_fed', 'GOVERNMENT', 'US'),
    ('actor_cb_eu_ecb', 'GOVERNMENT', 'EU'),
    ('actor_cb_jp_boj', 'GOVERNMENT', 'JP'),
    ('actor_inst_kr_krx', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_ksd', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_nps', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_kdb', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_nice', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_kis', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_kr_ratings', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_kftc', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_dtaq', 'INSTITUTION', 'KR'),
    ('actor_inst_kr_kisa', 'INSTITUTION', 'KR'),
    ('actor_auth_us_sec', 'GOVERNMENT', 'US'),
    ('actor_auth_us_fda', 'GOVERNMENT', 'US'),
    ('actor_auth_us_ftc', 'GOVERNMENT', 'US'),
    ('actor_auth_us_doc', 'GOVERNMENT', 'US'),
    ('actor_auth_us_doj', 'GOVERNMENT', 'US'),
    ('actor_auth_eu_commission', 'GOVERNMENT', 'EU'),
    ('actor_auth_cn_samr', 'GOVERNMENT', 'CN')
ON CONFLICT (actor_id) DO NOTHING;
