spring:
  application:
    name: app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55440/app}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6390}
      timeout: 500ms
